SELECT [id]
      ,[adiSoyadi]
      ,[firmaAdi]
      ,[tcKimlikNo]
      ,[vergiNo]
      ,[vergiDairesi]
      ,[ibanNo]
      ,[sektorAdi]
      ,[bankaAdi]
      ,[adres]
      ,[lokasyonAdi]
      ,[telefon]
      ,[email]
  FROM [dbo].[tblFirma]
  WHERE [id] = @id