SELECT [id]
      ,[personelAdiSoyadi]
      ,[idareAdi]
      ,[idareAmiri]
      ,[gorevi]
      ,[birim]
      ,[birimBaskani]
      ,[unvani]
      ,[muhasebeYetkilisi]
      ,[turu]
      ,[butce]
      ,[bakiye]
      ,[isinAdi]
      ,[ongorulenSure]
      ,[insertUser]
      ,[olurTarihi]
      ,[olurSayisi]
      ,[olurPdf]
      ,[istemTarihi]
      ,[komisyonTarihi]
      ,[ymcTarih]
      ,[yaklasikMaliyet]
      ,[satinalmaTalepTarihi]
      ,[harcamaOnayTarihi]
      ,[faturaTarihi]
      ,[faturaNo]
      ,[faturaPdf]
      ,[isinTeslimTarihi]
      ,[odemeEmriTarihi]
      ,[odemePdf]
      ,[kapat_flag]
  FROM [dbo].[tblDTS]
   WHERE [kapat_flag] IS NULL AND [id] = @id