SELECT [id]
      ,[dtsId]
      ,[idareAdi]
      ,[belgeSayisi]
      ,[belgeTarihi]
      ,[isinAdi]
      ,[isinNiteligi]
      ,[yatirimNo]
      ,[ihaleUsul]
      ,[ilanSekli]
      ,[ilanAdeti]
      ,[belgeBedeli]
      ,[butceTertibi]
      ,[tutar]
      ,[odenekTutari]
      ,[aciklama]
      ,[birimBaskani]
      ,[bbUnvani]
      ,[genelSekreter]
      ,[gsUnvani]
      ,[insertUser]
  FROM [dbo].[tblDTSHarcamaOnay]
    WHERE [dtsId] = @id