SELECT [id]
      ,[dtsId]
      ,[butceYili]
      ,[tarih]
      ,[emirNo]
      ,[istekliAdi]
      ,[tcKimlik]
      ,[bankaSubesi]
      ,[ibanNo]
      ,[belgeNo]
      ,[tutar]
      ,[kesintiToplam]
      ,[netOdenecek]
      ,[duzenleyen]
      ,[harcamaYetkilisi]
      ,[muhasebeYetkilisi]
  FROM [dbo].[tblOdeme]
  WHERE [dtsId] = @id