SELECT [id]
      ,[dtsId]
      ,[siraNo]
      ,[isinAdi]
      ,[gerekce]
      ,[yaklasikMaliyet]
      ,[vergiler]
      ,[butceTertibi]
      ,[serbestMiktar]
      ,[sure]
      ,[aciklama]
      ,[birimBaskani]
      ,[bbUnvani]
      ,[tarih]
      ,[muhasebeYetkilisi]
      ,[uygunTarih]
      ,[eklerId]
  FROM [dbo].[tblDTSSatinAlmaTalep]
  WHERE [dtsId] = @id