SELECT [id]
      ,[dtsId]
      ,[tarih]
      ,[yaklasikBedel]
      ,[kaynakAdi]
      ,[adres]
      ,[vergiDairesi]
      ,[vergiNumarasi]
      ,[telefon]
      ,[email]
      ,[ilgiliKisi]
      ,[nitelik]
      ,[kapsamNo]
      ,[kapsami]
      ,[yapilmaSebebi]
      ,[insertUser]
  FROM [dbo].[tblDTSTekKaynak]
   WHERE [dtsId]=@id IS NULL AND [insertUser]=@uID
