SELECT [id]
      ,[adiSoyadi]
      ,[email]
      ,[tcKimlik]
      ,[sicilNo]
      ,[cepTel]
      ,[iseGiris]
      ,[dogumGunu]
      ,[kanGrubu]
      ,[unvan]
      ,[birim]
      ,[photoURL]
      ,[username]
      ,[password]
      ,[isMod]
      ,[aktifPasif]
  FROM [dbo].[tblPersonel]
  WHERE aktifPasif ='A' AND [unvan] = 'Uzman' OR [unvan] = 'Koordinatör' OR [unvan] = 'Birim Başkanı'