SELECT [id]
      ,[donem]
      ,[baslangicTarihi]
      ,[bitisTarihi]
      ,[btKodu]
      ,[btAdi]
      ,[oncelik]
      ,[tedbir]
      ,[faaliyet]
      ,[sorumluBirim]
      ,[fonksiyonelDuzey]
      ,[butceTutar]
      ,[kullanilanTutar]
      ,[blokeTutar]
      ,[kalanTutar]
  FROM [dbo].[tblFaaliyet]
  WHERE [donem]=YEAR(GetDate())